# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('index', models.IntegerField()),
                ('isActive', models.BooleanField()),
            ],
        ),
    ]
