# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example1', '0002_auto_20170718_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataclass',
            options={'verbose_name': 'DataClass'},
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='abstractnut_ptr',
        ),
        migrations.AddField(
            model_name='dataclass',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
